# GitHub Action for converting Markdown to PDF and creating a release
name: Create Resume PDF

# Controls when the action will run
on:
  push:
    branches:
      - main # Or your default branch (e.g., master)
    paths:
      - 'resume.md' # Only runs when resume.md is changed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Converts markdown to PDF
      - name: Convert Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: . # The directory where the markdown files are
          output_dir: pdf # The directory to place the output PDF
          # Optional: specify a single input file
          input_file: resume.md
          # Optional: specify a custom output file name
          output_file: resume.pdf
          # Optional: add a table of contents
          table_of_contents: false

      # 3. Creates a Release and attaches the PDF
      - name: Create or Update Release with PDF
        uses: softprops/action-gh-release@v2
        with:
          # This is the name of the release
          name: Latest Resume
          # This is the tag for the release
          tag_name: latest-resume
          # Body of the release
          body: "Automatically generated resume from the latest commit."
          # This makes the release a "pre-release" if you want
          prerelease: false
          # This allows the action to overwrite a previous release with the same tag
          # This is key for keeping the "latest-resume" tag always up-to-date
          make_latest: true
          # These are the files to upload to the release
          files: |
            pdf/resume.pdf